# Generated by Selenium IDE
from exceptiongroup import catch
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import csv


class TestLogin:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self, accounts):
        test_case_result=[]

        for account in accounts:
            
            # Thực hiện login
            self.driver.get("https://www.saucedemo.com/")
            self.driver.find_element(By.CSS_SELECTOR, '*[data-test="username"]').send_keys(account["username"])
            self.driver.find_element(By.CSS_SELECTOR, '*[data-test="password"]').send_keys(account["password"])
            self.driver.find_element(By.CSS_SELECTOR, '*[data-test="login-button"]').click()
            
            result = ""
            
            try:
                # Kiểm tra kết quả kiểm thử
                error_message = self.driver.find_element(By.CSS_SELECTOR, '[data-test="error"]').text
                if error_message == "Epic sadface: Sorry, this user has been locked out.":
                    result = "locked"
                elif error_message == "Epic sadface: Username is required":
                    result = "username_empty"
                elif error_message == "Epic sadface: Password is required":
                    result = "password_empty"
                elif error_message == "Epic sadface: Username and password do not match any user in this service":
                    result = "not_match"
            except:
                result = "valid"

            # So sánh kết quả kiểm thử với kết quả mong muốn
            test_case_result.append(account["result"] == result)

        # Thống kê kết quả kiểm thử
        passed = test_case_result.count(True)

        # In kết quả
        expected = len(accounts)
        print(f"Passed: {passed}/{expected}")
    
    def read_csv(self, file_path):
        # Đọc file csv
        accounts = []

        with open(file_path, mode="r") as file:
            csv_reader = csv.DictReader(file)
            for row in csv_reader:
                accounts.append(
                    {
                        "username": row["username"],
                        "password": row["password"],
                        "result": row["result"],
                    }
                )

        # Thống kê kết quả mong muốn
            expected_result = {}

            for account in accounts:
                if account["result"] not in expected_result:
                    expected_result[account["result"]] = 0
                expected_result[account["result"]] += 1

            print("Expected result:")

            for result in expected_result:
                print(f"{result}: {expected_result[result]}")
        
        return accounts

if __name__ == "__main__":
    test = TestLogin()

    # Setup
    test.setup_method(None)
    
    # Thực hiện kiểm thử
    test.test_login(test.read_csv("./Kiểm Thử Phần Mềm/accounts.csv"))

    # Teardown
    test.teardown_method(None)
